-- Custom RBAC types
create type public.app_role as enum (
  'owner',
  'worker'
);

create type public.app_permission as enum (
  'dashboard.view.owner',
  'dashboard.view.worker',

  'profile.view.own',
  'profile.update.own',

  'worker.view',
  'worker.update',
  'worker.delete',

  'availability.view.own',
  'availability.update.own',
  'availability.view.all',

  'shift.create',
  'shift.update',
  'shift.cancel',
  'shift.view.all',
  'shift.view.own',
  'shift.accept',
  'shift.decline',
  'shift.view.history.own',

  'calendar.view',

  'document.view.own',
  'document.upload.own',

  'notification.view.owner',
  'notification.view.worker',
  'notification.filter',

  'cancellation.create.own',
  'cancellation.approve',
  'cancellation.reject',

  'help.view.owner',
  'help.view.worker'
);

-- Users assigned to application roles
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role public.app_role not null,
  unique (user_id)
);

comment on table public.user_roles is
  'Application role assigned to each authenticated user.';

-- Permissions assigned to roles
create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role public.app_role not null,
  permission public.app_permission not null,
  unique (role, permission)
);

comment on table public.role_permissions is
  'Permissions available to each application role.';

-- Owner permissions
insert into public.role_permissions (role, permission)
values
  ('owner', 'dashboard.view.owner'),
  ('owner', 'profile.view.own'),
  ('owner', 'profile.update.own'),
  ('owner', 'worker.view'),
  ('owner', 'worker.update'),
  ('owner', 'worker.delete'),
  ('owner', 'availability.view.all'),
  ('owner', 'shift.create'),
  ('owner', 'shift.update'),
  ('owner', 'shift.cancel'),
  ('owner', 'shift.view.all'),
  ('owner', 'calendar.view'),
  ('owner', 'notification.view.owner'),
  ('owner', 'notification.filter'),
  ('owner', 'cancellation.approve'),
  ('owner', 'cancellation.reject'),
  ('owner', 'help.view.owner');

-- Worker permissions
insert into public.role_permissions (role, permission)
values
  ('worker', 'dashboard.view.worker'),
  ('worker', 'profile.view.own'),
  ('worker', 'profile.update.own'),
  ('worker', 'availability.view.own'),
  ('worker', 'availability.update.own'),
  ('worker', 'shift.view.own'),
  ('worker', 'shift.accept'),
  ('worker', 'shift.decline'),
  ('worker', 'shift.view.history.own'),
  ('worker', 'calendar.view'),
  ('worker', 'document.view.own'),
  ('worker', 'document.upload.own'),
  ('worker', 'notification.view.worker'),
  ('worker', 'notification.filter'),
  ('worker', 'cancellation.create.own'),
  ('worker', 'help.view.worker');